# Exported from Render on 2024-12-19T08:03:00Z
databases:
- name: baseTestUserApi
  databaseName: basetestuserapi
  user: basetestuserapi_user
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: RenderCloudProject
  runtime: node
  repo: https://github.com/SeaniMoxxu/RenderCloudProject
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: baseTestUserApi
      property: connectionString
  region: frankfurt
  buildCommand: yarn
  startCommand: yarn start
version: "1"
